#!/bin/bash
function help {
      echo "Create a todo task marked as done"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    --help )
      help
      exit 2
      ;;
  esac
done;
ALL_PARAMS="$@"
DATE=`date +%Y-%m-%d`
#Actual functionality goes here.
echo "x $DATE $DATE @me $ALL_PARAMS" >> ~/.todo/done.txt

exit 0
