#!/bin/bash
function help {
      echo "Copy text file to clipboard"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

#Actual functionality goes here.
cat "$1"  | xclip -selection c
exit 0
