#!/bin/bash
function help {
      echo "resolve dependencies for all projects in directory"
      echo "    no argument defaults to working directory"
      echo " -d directory containing maven projects"
      echo " ? --help print this help"	
}

WORKDIR=`pwd`

for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    -d ) 
      ((i++))
      WORKDIR=${!i}
      ;;
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

if [ -z $WORKDIR ]; then
	echo "Not a valid directory"
	exit 1 
fi
if [ ! -d $WORKDIR ]; then
	echo "Directory doesn't exist"
	exit 1 
fi

cd $WORKDIR
find . -type f -name 'pom.xml' -print0 | xargs -0 -I SOURCES bash -c "echo SOURCES; mvn -T 5C dependency:resolve -f SOURCES;"
exit 0
