#!/bin/bash
function help {
      echo "Opens rbn in chrome window"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

google-chrome --profile-directory='Profile 1' --new-window --incognito https://instagram.com

exit 0
