#!/bin/bash
function help {
      echo "Opens page in incognito firefox window"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

firefox --private-window  "$@"

exit 0
