#!/bin/bash
function help {
      echo "Opens page in incognito rbn chrome window"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

google-chrome-stable --profile-directory=rbn --new-window --incognito  "$@"

exit 0
