#!/bin/bash
function help {
      echo "Sublime nano for quick notes"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

#Actual functionality goes here.
app snano nano -E -S -a -i -t -$ ~/.tmp.txt
exit 0
