#!/bin/bash
function help {
      echo "Opens blockers dashboard"
      echo " ? --help print this help"	
}

for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

google-chrome --profile-directory=Default --new-window  'http://jira.ziprealty.com/secure/Dashboard.jspa?selectPageId=12474'
exit 0
