#!/bin/bash
function help {
      echo "Reads from clipboard and generetes a separated line of issuekeys"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

echo $( xclip -o | sed 's/\s*Actions/, /g') | xclip -selection c

exit 0
