#!/bin/bash
function help {
      echo "Opens google chrome with tab to create deploy PRs "
      echo " -t Destination branch. Defaults to stage."
      echo " -f Origin branch. Defaults to development."
      echo " ? --help print this help"
}

ORIGIN="development"
DESTINY="stage"
CHROME_URL="http://stash.aur.ziprealty.com/dashboard"

for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
  -t )
    ((i++))
    DESTINY=${!i}
    ;;
  -f )
    ((i++))
     ORIGIN=${!i}
     ;;
  [?] | --help )
    help
    exit 2
    ;;
  * )
    echo "Invalid argument: ${!i}"
    help
    exit 2
    ;;
  esac
done;

for i in $(mdp-projects -1)
do
  project_details_array=($(echo  "$i" | tr ';' '\n'))
  CHROME_URL="$CHROME_URL http://stash.aur.ziprealty.com/projects/DP/repos/${project_details_array[0]}/pull-requests?create&targetBranch=refs%2Fheads%2F$DESTINY&sourceBranch=refs%2Fheads%2F$ORIGIN&targetRepoId=${project_details_array[1]}"
done

google-chrome --profile-directory=Default --new-window $CHROME_URL
exit 0
