#!/bin/bash
function help {
      echo "This is help"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

cat /home/roberto.delvalle/mls/mls.master | parallel -j2% -n1 export-canonical {}

exit 0
