#!/bin/bash
function help {
      echo "Opens jira pages"
      echo " ? --help print this help"	
}

for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

g  'http://jira.ziprealty.com/secure/RapidBoard.jspa?rapidView=545' 'http://jira.ziprealty.com/secure/Dashboard.jspa?selectPageId=12473' 'http://jira.ziprealty.com/secure/ManageFilters.jspa?filterView=favourites'

exit 0
