#!/bin/bash
function help {
      echo "Opens MDP jira issue in chrome window"
      echo " ? --help print this help"	
}

tkts=""
for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

for i in $(printf '%s\n' "$@" | sort | uniq)
do
  tkts=$tkts"  http://jira.ziprealty.com/browse/MDP-$i"

done

g $tkts

exit 0
