#!/bin/bash
function help {
      echo "Opens MDP jira issue in chrome window"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      TKT=$1
      ;;
  esac
done;

google-chrome --profile-directory=Default --new-window  --disable-setuid-sandbox --app=http://jira.ziprealty.com/browse/MDP-$TKT

exit 0
