#!/bin/bash
function help {
      echo "Opens google chrome with tabs to monitor rentalcom builds"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

google-chrome --profile-directory=Default --new-window  http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/nifi-zap/job/rentalcom/ http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/mls-data-platform-sync/job/rentalcom/ http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/mls-data-platform/job/rentalcom/ http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/mls-dataplatform-mongoconnector/job/rentalcom/ http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/mls-dataplatform-transformations/job/rentalcom/ http://jenkins-master.aur.ziprealty.com/job/Data%20Platform/job/mls_data_platform_web_ui/job/rentalcom/

exit 0
