#!/bin/bash
function help {
      echo "When copying from cloudwath substitute single quote with double quotes and pretty print"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

echo `xclip -o ` | sed 's/null/null/gI' | sed 's/false/false/gI' | sed 's/true/true/gI'  | sed s/\'/\"/g | python -m json.tool

exit 0
