#!/bin/bash
function help {
      echo "Opens stash in chrome window"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

google-chrome --profile-directory=Default --new-window  http://stash.aur.ziprealty.com:7990/dashboard

exit 0
