#!/bin/bash
function help {
      echo "Reads from clipboard and generetes a separated line of issuekeys"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

g "http://jira.ziprealty.com/issues/?filter=15339&jql=project%20%3D%20MDP%20AND%20status%20!%3D%20Done%20AND%20issuekey%20in%20($(cblockers))%20ORDER%20BY%20status%20DESC%2C%20\"Epic%20Link\"%20ASC%2C%20Rank%20ASC"
exit 0
