#!/bin/bash
function help {
      echo "List tasks completed yesterday"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

#Actual functionality goes here.
cat ~/.todo-txt/done.txt

exit 0
