#!/bin/bash
function help {
  echo "This is help"
  echo " ? --help print this help"
}

environments_list="qa stage rentalcom prod"
clients_list="postgres oracle mysql"


function list_environments{
  echo $environments_list
}

functien list_clients{
  echo $clients_list
}




for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

exit 0
