#!/bin/bash
function help {
      echo "This is morning pages"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
    * )
      echo "Invalid argument: ${!i}"
      help
      exit 2
      ;;
  esac
done;

#Actual functionality goes here.
gnome-terminal --hide-menubar -t "pdm" -- nano -E -S -a -i -l -t -$ +1,3 ~/pdm/$(date +%Y%m%d)
exit 0
