#!/bin/bash
function help {
      echo "Set window tittle"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    --help )
      help
      exit 2
      ;;
  esac
done;
#Actual functionality goes here.
wmctrl -r :ACTIVE: -N "$@"

exit 0
