#!/bin/bash
function help {
      echo "runs passed command on a standalone terminal window as if it were an app"
      echo " ? --help print this help"	
}


for ((i=1;i<=$#;i++));
do
  parameter=${!i}
  case $parameter in
    [?] | --help )
      help
      exit 2
      ;;
  esac
done;

#Actual functionality goes here.
tittle=$1
shift 1
executable="$@"
xfce4-terminal -T "$tittle" --hide-borders --hide-toolbar --hide-scrollbar --hide-menubar $([[ "$tittle" == "spotify" ]] && echo " --geometry 80x24+3100+0") -e "$executable"
exit 0
